[tools]
node = ["22.16.0", "20.9.0", "18.12.1"]
pnpm = "latest"
ruby = "3.4.4"
rust = "1.87.0"
biome = "1.9.4"
golang = ["1.25.3"]
java = ["21"]

[settings]
idiomatic_version_file_enable_tools = ["python"]
