
name: Installation and Setup Check

on:
  push:

jobs:
  installation-and-setup-check:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: check brew tap, brew and cask package installation
        run: make brew-bundle-ci

      - name: check asdf plugins installation
        run: make asdf-plugins

      - name: check symbolic linking
        run: make stow-packages
