name: Installation and Setup Check

on:
  push:
    branches: [main]

jobs:
  installation-and-setup-check:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: check brew tap, brew and cask package installation
        run: make brew-bundle-ci

      - name: check symbolic linking
        run: make stow-packages
